#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# One-command Docker installer for a Hostinger VPS (any Linux with Docker, or Ubuntu/Debian
# where Docker will be installed for you).
#
#   curl -fsSL https://raw.githubusercontent.com/mastersa3d/ads.dashboard.attract/claude/exciting-bohr-a14mwz/scripts/install-docker-vps.sh -o install-docker.sh
#   sudo bash install-docker.sh
#
# Runs the stack in docker-compose.yml: PostgreSQL + app + worker + Caddy (automatic HTTPS).
# Generates .env.production with random secrets, creates your organization + first Super Admin
# (no demo data) and schedules a daily database/uploads backup.
# Re-running is safe: secrets and data are kept, the code and containers are updated.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/mastersa3d/ads.dashboard.attract.git}"
BRANCH="${BRANCH:-claude/exciting-bohr-a14mwz}"
APP_DIR="${APP_DIR:-/opt/mimd-docker}"
ENV_FILE="$APP_DIR/.env.production"

say() { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }
[[ $EUID -eq 0 ]] || die "Run as root: sudo bash install-docker.sh"

# ── 1. Docker + git ──────────────────────────────────────────────────────────
if ! command -v docker >/dev/null; then
  say "Installing Docker"
  curl -fsSL https://get.docker.com | sh
fi
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is missing (docker compose). Install the docker-compose-plugin package."
command -v git >/dev/null || { command -v apt-get >/dev/null && apt-get update -y && apt-get install -y git; } || die "Install git first."
systemctl enable --now docker >/dev/null 2>&1 || true

# ── 2. Code ──────────────────────────────────────────────────────────────────
if [[ -d "$APP_DIR/.git" ]]; then
  say "Updating code ($BRANCH)"
  git -C "$APP_DIR" fetch --depth 1 origin "$BRANCH"
  git -C "$APP_DIR" reset --hard "origin/$BRANCH"
else
  say "Downloading code ($BRANCH)"
  git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
fi
cd "$APP_DIR"

# ── 3. Settings (first install only) ─────────────────────────────────────────
FIRST_INSTALL=0
if [[ ! -f "$ENV_FILE" ]]; then
  FIRST_INSTALL=1
  PUBLIC_IP="$(curl -fsS4 --max-time 5 https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')"
  if [[ -z "${DOMAIN+set}" ]]; then
    echo
    echo "Domain for the platform (e.g. app.yourcompany.com)."
    echo "Its DNS A record must point to this server ($PUBLIC_IP) so HTTPS can be issued."
    read -rp "Domain (leave empty to use http://$PUBLIC_IP for now): " DOMAIN < /dev/tty || DOMAIN=""
  fi
  [[ -n "${ORG_NAME:-}" ]] || read -rp "Company / agency name: " ORG_NAME < /dev/tty
  [[ -n "${ADMIN_EMAIL:-}" ]] || read -rp "Super Admin e-mail: " ADMIN_EMAIL < /dev/tty
  if [[ -z "${ADMIN_PASSWORD:-}" ]]; then
    while true; do
      read -rsp "Super Admin password (10+ chars, letters and digits): " ADMIN_PASSWORD < /dev/tty; echo
      read -rsp "Repeat password: " P2 < /dev/tty; echo
      [[ "$ADMIN_PASSWORD" == "$P2" ]] || { echo "Passwords don't match."; continue; }
      [[ ${#ADMIN_PASSWORD} -ge 10 && "$ADMIN_PASSWORD" =~ [A-Za-z] && "$ADMIN_PASSWORD" =~ [0-9] ]] && break
      echo "Too weak — use 10+ characters with letters and digits."
    done
  fi
  [[ -n "$ORG_NAME" && "$ADMIN_EMAIL" == *@* ]] || die "Company name and a valid e-mail are required."
  [[ "$ADMIN_PASSWORD" != *\'* ]] || die "Please don't use the ' character in the password."

  if [[ -n "${DOMAIN:-}" ]]; then SITE="$DOMAIN"; APP_URL="https://$DOMAIN"; else SITE=":80"; APP_URL="http://$PUBLIC_IP"; fi
  say "Writing $ENV_FILE"
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/install-docker-vps.sh on $(date -u +%F). Keep this file secret.
DOMAIN=$SITE
APP_URL=$APP_URL
ACME_EMAIL=$ADMIN_EMAIL
POSTGRES_USER=mimd
POSTGRES_DB=mimd
POSTGRES_PASSWORD=$(openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')
ENCRYPTION_KEY=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)
CRON_SECRET=$(openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')
NEXT_PUBLIC_APP_NAME='Marketing Intelligence'
DEFAULT_LOCALE=ar
# First-boot admin (used once, then cleared by the installer)
ORG_NAME='$ORG_NAME'
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD='$ADMIN_PASSWORD'
# Optional — fill in, then run: sudo bash $APP_DIR/scripts/install-docker-vps.sh
SMTP_HOST=
SMTP_PORT=465
SMTP_USER=
SMTP_PASSWORD=
MAIL_FROM=
ANTHROPIC_API_KEY=
META_APP_ID=
META_APP_SECRET=
META_AD_LIBRARY_TOKEN=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_ADS_DEVELOPER_TOKEN=
TIKTOK_APP_ID=
TIKTOK_APP_SECRET=
LINKEDIN_CLIENT_ID=
LINKEDIN_CLIENT_SECRET=
EOF
  umask 022
  unset ADMIN_PASSWORD P2
fi

# `.env` → `.env.production` so plain `docker compose …` (and scripts/backup.sh in docker mode)
# find the same settings without --env-file.
ln -sfn .env.production "$APP_DIR/.env"

# ── 4. Ports 80/443 must be free for Caddy ───────────────────────────────────
if [[ $FIRST_INSTALL -eq 1 ]] && command -v ss >/dev/null; then
  BUSY="$(ss -ltnp 2>/dev/null | awk '$4 ~ /:(80|443)$/ {print $4" "$6}' | grep -v docker-proxy || true)"
  [[ -z "$BUSY" ]] || die "Ports 80/443 are already used by another program:
$BUSY
Stop it first (e.g. 'systemctl disable --now nginx apache2 caddy'), then run this script again."
fi

# ── 5. Build + start ─────────────────────────────────────────────────────────
say "Building and starting containers (first time takes 5–10 minutes)"
if [[ $FIRST_INSTALL -eq 0 && -x scripts/backup.sh ]] && docker compose --env-file "$ENV_FILE" ps --status running db 2>/dev/null | grep -q db; then
  BACKUP_MODE=docker SKIP_DOTENV=1 POSTGRES_USER=mimd POSTGRES_DB=mimd BACKUP_DIR="$APP_DIR/backups" bash scripts/backup.sh || echo "(backup before update failed — continuing)"
fi
docker compose --env-file "$ENV_FILE" up -d --build --remove-orphans

# ── 6. Health check ──────────────────────────────────────────────────────────
say "Waiting for the app to become healthy"
OK=0
for _ in $(seq 1 90); do
  if docker compose --env-file "$ENV_FILE" exec -T app wget -Y off -qO- http://127.0.0.1:3000/api/health >/dev/null 2>&1; then OK=1; break; fi
  sleep 3
done
if [[ $OK -ne 1 ]]; then
  docker compose --env-file "$ENV_FILE" logs --tail 60 migrate app || true
  die "The app did not become healthy (logs above)."
fi
docker compose --env-file "$ENV_FILE" logs migrate 2>/dev/null | grep -E "bootstrap:" | tail -1 || true

# The admin password is only needed for the first boot — remove it from disk.
sed -i "s/^ADMIN_PASSWORD=.*/ADMIN_PASSWORD=/" "$ENV_FILE"
chmod 600 "$ENV_FILE"

# ── 7. Daily backup ──────────────────────────────────────────────────────────
cat > /etc/cron.d/mimd-docker-backup <<EOF
# Daily database + uploads backup at 03:15 (kept 14 days, weekly copies 8 weeks)
15 3 * * * root cd $APP_DIR && BACKUP_MODE=docker SKIP_DOTENV=1 POSTGRES_USER=mimd POSTGRES_DB=mimd BACKUP_DIR=$APP_DIR/backups bash scripts/backup.sh >> $APP_DIR/backups/backup.log 2>&1
EOF
mkdir -p "$APP_DIR/backups"

set -a; source "$ENV_FILE"; set +a
echo
printf '\033[1;32m✔ Running in Docker.\033[0m  Open: %s\n' "$APP_URL"
echo "  Status:  cd $APP_DIR && docker compose ps"
echo "  Logs:    cd $APP_DIR && docker compose logs -f app worker"
echo "  Update:  sudo bash $APP_DIR/scripts/install-docker-vps.sh   (keeps data and secrets)"
echo "  Secrets: $ENV_FILE (SMTP, AI and platform API keys go here)"
